spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port : 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/